"""empty message

Revision ID: a368290a4bfd
Revises: 206f7969828d
Create Date: 2019-11-25 23:37:26.392407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a368290a4bfd'
down_revision = '206f7969828d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.ARRAY(sa.String(length=120)), nullable=True))
    op.drop_column('Artist', 'address')
    op.add_column('Venue', sa.Column('genres', sa.ARRAY(sa.String(length=120)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    op.add_column('Artist', sa.Column('address', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###
